/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/tabeth/concretesql/cmd/concretesql-extension */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"


#include <string.h>
#include <stdlib.h>
#include "sqlite3ext.h"

// function implemented in extension_init.c
int register_concretesql_vfs(const char *name);

#line 1 "cgo-generated-wrapper"

#line 3 "vfs_bridge.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int InitConcreteSQLVFS(sqlite3* db, char** pzErrMsg, sqlite3_api_routines* pApi);
extern int go_vfs_open(char* name, void** fileOut, int flags, int* outFlags);
extern int go_vfs_delete(char* name, int syncDir);
extern int go_vfs_access(char* name, int flags, int* pResOut);
extern int go_vfs_full_pathname(char* name, int nOut, char* zOut);
extern int go_file_close(void* p);
extern int go_file_read(void* p, void* buf, int iAmt, long long int iOfst);
extern int go_file_write(void* p, void* buf, int iAmt, long long int iOfst);
extern int go_file_truncate(void* p, long long int size);
extern int go_file_sync(void* p, int flags);
extern int go_file_file_size(void* p, long long int* pSize);
extern int go_file_lock(void* p, int lock);
extern int go_file_unlock(void* p, int lock);
extern int go_file_check_reserved_lock(void* p, int* pResOut);
extern int go_file_sector_size(void* p);
extern int go_file_device_characteristics(void* p);

#ifdef __cplusplus
}
#endif
